REQUESTED = 'REQUESTED'
STARTED = 'STARTED'
IN_PROGRESS = 'IN_PROGRESS'
COMPLETED = 'COMPLETED'
STATUSES = (
    (REQUESTED, REQUESTED),
    (STARTED, STARTED),
    (IN_PROGRESS, IN_PROGRESS),
    (COMPLETED, COMPLETED),
)